# Generated by Django 4.2.7 on 2023-11-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.TextField()),
                ('conference_id', models.IntegerField()),
                ('author_ids', models.IntegerField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.IntegerField()),
                ('reviewer_id', models.IntegerField()),
                ('score', models.IntegerField()),
                ('comment', models.TextField()),
                ('decision', models.CharField(max_length=50)),
            ],
        ),
    ]
