# Generated by Django 4.2.7 on 2023-12-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_service', '0002_alter_review_comment_alter_review_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='confidence',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
