# Generated by Django 4.2.5 on 2023-12-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_service', '0003_review_confidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='author_ids',
        ),
        migrations.AddField(
            model_name='paper',
            name='author_info',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='paper',
            name='submitted_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='topics',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pdf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
