# Generated by Django 4.2.5 on 2023-12-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_service', '0004_remove_paper_author_ids_paper_author_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
