# Generated by Django 4.2.5 on 2023-12-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_service', '0005_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rebuttal',
            field=models.TextField(blank=True),
        ),
    ]
