# Generated by Django 4.2.5 on 2023-12-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_service', '0006_review_rebuttal'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='conference_id',
            field=models.IntegerField(null=True),
        ),
    ]
