# Generated by Django 4.2.5 on 2023-12-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_service', '0007_review_conference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='conference_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
