# Generated by Django 4.2.7 on 2023-11-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('submission_deadline', models.DateTimeField()),
                ('review_deadline', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('chair_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PCMemberInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_id', models.IntegerField()),
                ('pc_member_id', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=50)),
            ],
        ),
    ]
