# Generated by Django 4.2.7 on 2023-11-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='end_date',
            new_name='held_date',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='start_date',
        ),
    ]
