# Generated by Django 4.2.7 on 2023-11-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_service', '0002_rename_end_date_conference_held_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_id', models.IntegerField()),
                ('invitee_id', models.IntegerField()),
                ('pc_member_id', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='PCMemberInvitation',
        ),
    ]
