# Generated by Django 4.2.7 on 2023-11-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_service', '0003_invitation_delete_pcmemberinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='topics',
            field=models.TextField(default='deep learning'),
            preserve_default=False,
        ),
    ]
