# Generated by Django 4.2.7 on 2023-12-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_service', '0004_conference_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='accepted_topics',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
